Upload6

diff --git a/.github/workflows/main_MSIX.yml b/.github/workflows/main_MSIX.yml
--- a/.github/workflows/main_MSIX.yml
+++ b/.github/workflows/main_MSIX.yml
@@ -14,7 +14,15 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v3
         
-      
+      - name: Check
+        shell: powershell
+        run: |
+          if (!(Test-Path "C:\Program Files (x86)\WinSCP\winscp.com")) {
+            echo "ERROR: psftp.exe not found!"
+            exit 1
+          } else {
+            echo "PuTTY psftp.exe found!"
+          }
       
       - name: Upload MSI to SFTP Server using WinSCP
         shell: powershell
